/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/base64': RouteRecordInfo<
      '/base64',
      '/base64',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bilidown': RouteRecordInfo<
      '/bilidown',
      '/bilidown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories': RouteRecordInfo<
      '/categories',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dydown': RouteRecordInfo<
      '/dydown',
      '/dydown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/exif': RouteRecordInfo<
      '/exif',
      '/exif',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hok': RouteRecordInfo<
      '/hok',
      '/hok',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jichacha': RouteRecordInfo<
      '/jichacha',
      '/jichacha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/json-yaml': RouteRecordInfo<
      '/json-yaml',
      '/json-yaml',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/lyric': RouteRecordInfo<
      '/lyric',
      '/lyric',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/playground': RouteRecordInfo<
      '/playground',
      '/playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qrcode': RouteRecordInfo<
      '/qrcode',
      '/qrcode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reaction': RouteRecordInfo<
      '/reaction',
      '/reaction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/weather': RouteRecordInfo<
      '/weather',
      '/weather',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/base64.vue': {
      routes:
        | '/base64'
      views:
        | never
    }
    'src/pages/bilidown.vue': {
      routes:
        | '/bilidown'
      views:
        | never
    }
    'src/pages/categories.vue': {
      routes:
        | '/categories'
      views:
        | never
    }
    'src/pages/dydown.vue': {
      routes:
        | '/dydown'
      views:
        | never
    }
    'src/pages/exif.vue': {
      routes:
        | '/exif'
      views:
        | never
    }
    'src/pages/hok.vue': {
      routes:
        | '/hok'
      views:
        | never
    }
    'src/pages/jichacha.vue': {
      routes:
        | '/jichacha'
      views:
        | never
    }
    'src/pages/json-yaml.vue': {
      routes:
        | '/json-yaml'
      views:
        | never
    }
    'src/pages/lyric.vue': {
      routes:
        | '/lyric'
      views:
        | never
    }
    'src/pages/playground.vue': {
      routes:
        | '/playground'
      views:
        | never
    }
    'src/pages/qrcode.vue': {
      routes:
        | '/qrcode'
      views:
        | never
    }
    'src/pages/reaction.vue': {
      routes:
        | '/reaction'
      views:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
    }
    'src/pages/weather.vue': {
      routes:
        | '/weather'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
