import type { Component } from 'vue'
import {
  Code2,
  FileType,
  Play,
  QrCode,
  Camera,
  Video,
  Music,
  CloudSun,
  Swords,
  Zap,
  Smartphone,
  Gamepad2,
  Image,
  MessageCircle,
  BadgeDollarSign,
  ArrowRightLeft,
  Ruler,
  Activity,
  Clock,
  Volume2,
  CalendarDays,
  BookOpen,
  Search,
  Link,
  MapPin,
  Hash,
  Users,
} from 'lucide-vue-next'

export interface Tool {
  id: string
  title: string // i18n key, e.g. 'tools.base64.title'
  subtitle: string // i18n key
  description: string // i18n key
  author: string
  usage: string // i18n key
  icon: Component
  color: string
  path: string
  date: string
  backEnd?: string
  license?: string
  copyright?: string
}

export const default_license = 'MIT License'
export const default_copyright = ''

export const tops = ['ncm-get-playlist', 'hhsh', 'exchange', 'length']

export const hots = [
  'ncm-get-playlist',
  'dydown',
  'bilidown',
  'lyric',
  'jichacha',
  'weibo-hot',
  'hok',
]

export const toolsData: Record<string, Tool[]> = {
  dev: [
    {
      id: 'adoc',
      title: 'tools.adoc.title',
      subtitle: 'tools.adoc.subtitle',
      description: 'tools.adoc.description',
      author: 'Yule',
      usage: 'tools.adoc.usage',
      icon: MapPin,
      color: 'text-emerald-500',
      path: '/adoc',
      date: '2026-03-23',
    },
    {
      id: 'url-encode',
      title: 'tools.url-encode.title',
      subtitle: 'tools.url-encode.subtitle',
      description: 'tools.url-encode.description',
      author: 'Yule',
      usage: 'tools.url-encode.usage',
      icon: Link,
      color: 'text-cyan-500',
      path: '/url-encode',
      date: '2026-03-23',
    },
    {
      id: 'unicode',
      title: 'tools.unicode.title',
      subtitle: 'tools.unicode.subtitle',
      description: 'tools.unicode.description',
      author: 'Yule',
      usage: 'tools.unicode.usage',
      icon: Hash,
      color: 'text-blue-400',
      path: '/unicode',
      date: '2026-03-23',
    },
    {
      id: 'base64',
      title: 'tools.base64.title',
      subtitle: 'tools.base64.subtitle',
      description: 'tools.base64.description',
      author: 'Yule',
      usage: 'tools.base64.usage',
      icon: Code2,
      color: 'text-blue-500',
      path: '/base64',
      date: '2026-01-01',
    },
    {
      id: 'json-yaml',
      title: 'tools.json-yaml.title',
      subtitle: 'tools.json-yaml.subtitle',
      description: 'tools.json-yaml.description',
      author: 'Yule',
      usage: 'tools.json-yaml.usage',
      icon: FileType,
      color: 'text-indigo-500',
      path: '/json-yaml',
      date: '2026-01-02',
    },
    {
      id: 'markdown-table-csv',
      title: 'tools.markdown-table-csv.title',
      subtitle: 'tools.markdown-table-csv.subtitle',
      description: 'tools.markdown-table-csv.description',
      author: 'Yule',
      usage: 'tools.markdown-table-csv.usage',
      icon: FileType,
      color: 'text-teal-500',
      path: '/markdown-table-csv',
      date: '2026-04-09',
    },
    {
      id: 'playground',
      title: 'tools.playground.title',
      subtitle: 'tools.playground.subtitle',
      description: 'tools.playground.description',
      author: 'Yule',
      usage: 'tools.playground.usage',
      icon: Play,
      color: 'text-blue-600',
      path: '/playground',
      date: '2026-01-27',
    },
    {
      id: 'translator-ai',
      title: 'tools.translator-ai.title',
      subtitle: 'tools.translator-ai.subtitle',
      description: 'tools.translator-ai.description',
      author: 'Yule',
      usage: 'tools.translator-ai.usage',
      icon: FileType,
      color: 'text-blue-500',
      path: '/translator-ai',
      date: '2026-02-22',
    },
    {
      id: 'codeimg',
      title: 'tools.codeimg.title',
      subtitle: 'tools.codeimg.subtitle',
      description: 'tools.codeimg.description',
      author: 'Yule',
      usage: 'tools.codeimg.usage',
      icon: Image,
      color: 'text-blue-500',
      path: '/codeimg',
      date: '2026-02-22',
    },
  ],
  media: [
    {
      id: 'qrcode',
      title: 'tools.qrcode.title',
      subtitle: 'tools.qrcode.subtitle',
      description: 'tools.qrcode.description',
      author: 'Yule',
      usage: 'tools.qrcode.usage',
      icon: QrCode,
      color: 'text-slate-700 dark:text-slate-300',
      path: '/qrcode',
      date: '2026-01-03',
    },
    {
      id: 'exif',
      title: 'tools.exif.title',
      subtitle: 'tools.exif.subtitle',
      description: 'tools.exif.description',
      author: 'Yule',
      usage: 'tools.exif.usage',
      icon: Camera,
      color: 'text-rose-500',
      path: '/exif',
      date: '2026-01-26',
    },
    {
      id: 'dydown',
      title: 'tools.dydown.title',
      subtitle: 'tools.dydown.subtitle',
      description: 'tools.dydown.description',
      author: 'Yule',
      usage: 'tools.dydown.usage',
      icon: Video,
      color: 'text-pink-500',
      path: '/dydown',
      backEnd:
        'https://github.com/YuleBest/xiaoyu-toolbox/blob/main/src/back-end/cf-workers/dydown.js',
      date: '2026-01-25',
    },
    {
      id: 'bilidown',
      title: 'tools.bilidown.title',
      subtitle: 'tools.bilidown.subtitle',
      description: 'tools.bilidown.description',
      author: 'Yule',
      usage: 'tools.bilidown.usage',
      icon: Video,
      color: 'text-sky-400',
      path: '/bilidown',
      backEnd:
        'https://github.com/YuleBest/xiaoyu-toolbox/blob/main/src/back-end/cf-workers/bilidown.js',
      date: '2026-01-27',
    },
    {
      id: 'bvav',
      title: 'tools.bvav.title',
      subtitle: 'tools.bvav.subtitle',
      description: 'tools.bvav.description',
      author: 'Yule',
      usage: 'tools.bvav.usage',
      icon: ArrowRightLeft,
      color: 'text-pink-400',
      path: '/bvav',
      date: '2026-02-27',
    },
    {
      id: 'lyric',
      title: 'tools.lyric.title',
      subtitle: 'tools.lyric.subtitle',
      description: 'tools.lyric.description',
      author: 'Yule',
      usage: 'tools.lyric.usage',
      icon: Music,
      color: 'text-orange-500',
      path: '/lyric',
      backEnd:
        'https://github.com/YuleBest/xiaoyu-toolbox/blob/main/src/back-end/cf-workers/getlyric.js',
      date: '2026-02-13',
    },
    {
      id: 'ncm-get-playlist',
      title: 'tools.ncm-get-playlist.title',
      subtitle: 'tools.ncm-get-playlist.subtitle',
      description: 'tools.ncm-get-playlist.description',
      author: 'Yule',
      usage: 'tools.ncm-get-playlist.usage',
      icon: Music,
      color: 'text-red-500',
      path: '/ncm-get-playlist',
      date: '2026-02-28',
    },
    {
      id: 'anime-search',
      title: 'tools.anime-search.title',
      subtitle: 'tools.anime-search.subtitle',
      description: 'tools.anime-search.description',
      author: 'Yule',
      usage: 'tools.anime-search.usage',
      icon: Search,
      color: 'text-indigo-500',
      path: '/anime-search',
      backEnd: 'https://trace.moe/',
      date: '2026-03-18',
    },
  ],
  life: [
    {
      id: 'hhsh',
      title: 'tools.hhsh.title',
      subtitle: 'tools.hhsh.subtitle',
      description: 'tools.hhsh.description',
      author: 'Yule',
      usage: 'tools.hhsh.usage',
      icon: MessageCircle,
      color: 'text-blue-500',
      path: '/hhsh',
      backEnd: '/api/hhsh/guess',
      date: '2026-02-22',
      license: 'Apache License 2.0',
    },
    {
      id: 'jichacha',
      title: 'tools.jichacha.title',
      subtitle: 'tools.jichacha.subtitle',
      description: 'tools.jichacha.description',
      author: 'Yule',
      usage: 'tools.jichacha.usage',
      icon: Smartphone,
      color: 'text-emerald-500',
      path: '/jichacha',
      backEnd: '/api/jichacha',
      date: '2026-02-19',
      license: 'CC BY-NC-SA 4.0',
      copyright:
        '本工具的数据源自 https://github.com/KHwang9883/MobileModels ，基于 CC BY-NC-SA 4.0 授权。',
    },
    {
      id: 'weather',
      title: 'tools.weather.title',
      subtitle: 'tools.weather.subtitle',
      description: 'tools.weather.description',
      author: 'Yule',
      usage: 'tools.weather.usage',
      icon: CloudSun,
      color: 'text-amber-400',
      path: '/weather',
      backEnd: 'https://open-meteo.com/',
      date: '2026-01-20',
    },
    {
      id: 'exchange',
      title: 'tools.exchange.title',
      subtitle: 'tools.exchange.subtitle',
      description: 'tools.exchange.description',
      author: 'Yule',
      usage: 'tools.exchange.usage',
      icon: BadgeDollarSign,
      color: 'text-blue-500',
      path: '/exchange',
      backEnd: '/api/frankfurter',
      date: '2026-02-24',
    },
    {
      id: 'length',
      title: 'tools.length.title',
      subtitle: 'tools.length.subtitle',
      description: 'tools.length.description',
      author: 'Yule',
      usage: 'tools.length.usage',
      icon: Ruler,
      color: 'text-purple-500',
      path: '/length',
      date: '2026-02-28',
    },
    {
      id: 'phone-number',
      title: 'tools.phone-number.title',
      subtitle: 'tools.phone-number.subtitle',
      description: 'tools.phone-number.description',
      author: 'Yule',
      usage: 'tools.phone-number.usage',
      icon: Smartphone,
      color: 'text-teal-500',
      path: '/phone-number',
      date: '2026-02-25',
    },
    {
      id: 'weibo-hot',
      title: 'tools.weibo-hot.title',
      subtitle: 'tools.weibo-hot.subtitle',
      description: 'tools.weibo-hot.description',
      author: 'Yule',
      usage: 'tools.weibo-hot.usage',
      icon: Zap,
      color: 'text-orange-500',
      path: '/weibo-hot',
      date: '2026-02-26',
    },
    {
      id: 'period',
      title: 'tools.period.title',
      subtitle: 'tools.period.subtitle',
      description: 'tools.period.description',
      author: 'Yule',
      usage: 'tools.period.usage',
      icon: Activity,
      color: 'text-rose-400',
      path: '/period',
      date: '2026-02-28',
    },
    {
      id: 'time-distance',
      title: 'tools.time-distance.title',
      subtitle: 'tools.time-distance.subtitle',
      description: 'tools.time-distance.description',
      author: 'Yule',
      usage: 'tools.time-distance.usage',
      icon: Clock,
      color: 'text-sky-500',
      path: '/time-distance',
      date: '2026-03-01',
    },
    {
      id: 'statutory-holidays',
      title: 'tools.statutory-holidays.title',
      subtitle: 'tools.statutory-holidays.subtitle',
      description: 'tools.statutory-holidays.description',
      author: 'Yule',
      usage: 'tools.statutory-holidays.usage',
      icon: CalendarDays,
      color: 'text-blue-500',
      path: '/statutory-holidays',
      date: '2026-03-06',
    },
    {
      id: 'poetry',
      title: 'tools.poetry.title',
      subtitle: 'tools.poetry.subtitle',
      description: 'tools.poetry.description',
      author: 'Yule',
      usage: 'tools.poetry.usage',
      icon: BookOpen,
      color: 'text-emerald-600',
      path: '/poetry',
      date: '2026-03-07',
    },
    {
      id: 'china-demographics',
      title: 'tools.china-demographics.title',
      subtitle: 'tools.china-demographics.subtitle',
      description: 'tools.china-demographics.description',
      author: 'Yule',
      usage: 'tools.china-demographics.usage',
      icon: Users,
      color: 'text-red-500',
      path: '/china-demographics',
      date: '2026-04-09',
      license: 'CC BY 4.0',
      copyright: '数据来源：中国国家统计局，基于 CC BY 4.0 授权使用。',
    },
  ],
  game: [
    {
      id: 'hok',
      title: 'tools.hok.title',
      subtitle: 'tools.hok.subtitle',
      description: 'tools.hok.description',
      author: 'Yule',
      usage: 'tools.hok.usage',
      icon: Swords,
      color: 'text-violet-500',
      path: '/hok',
      backEnd: 'https://github.com/YuleBest/GetHOK',
      date: '2026-01-28',
    },
    {
      id: 'hok-voices',
      title: 'tools.hok-voices.title',
      subtitle: 'tools.hok-voices.subtitle',
      description: 'tools.hok-voices.description',
      author: 'Yule',
      usage: 'tools.hok-voices.usage',
      icon: Volume2,
      color: 'text-blue-500',
      path: '/hok-voices',
      date: '2026-03-04',
    },
    {
      id: 'reaction',
      title: 'tools.reaction.title',
      subtitle: 'tools.reaction.subtitle',
      description: 'tools.reaction.description',
      author: 'Yule',
      usage: 'tools.reaction.usage',
      icon: Zap,
      color: 'text-yellow-500',
      path: '/reaction',
      date: '2026-01-28',
    },
    {
      id: 'mcpe',
      title: 'tools.mcpe.title',
      subtitle: 'tools.mcpe.subtitle',
      description: 'tools.mcpe.description',
      author: 'Yule',
      usage: 'tools.mcpe.usage',
      icon: Gamepad2,
      color: 'text-blue-500',
      path: '/mcpe',
      backEnd: '/api/getmcpe',
      date: '2026-02-21',
    },
  ],
}

export const allTools = Object.values(toolsData).flat()
