/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/layout/BackButton.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    LanguageToggle: typeof import('./components/LanguageToggle.vue')['default']
    MobileNav: typeof import('./components/layout/MobileNav.vue')['default']
    ModeToggle: typeof import('./components/ModeToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./components/ui/scroll-area/ScrollBar.vue')['default']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./components/ui/sheet/SheetTrigger.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    Sonner: typeof import('./components/ui/sonner/Sonner.vue')['default']
    ToolContainer: typeof import('./components/tool/ToolContainer.vue')['default']
  }
}
