/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/base64/': RouteRecordInfo<'/base64/', '/base64', Record<never, never>, Record<never, never>>,
    '/bilidown/': RouteRecordInfo<'/bilidown/', '/bilidown', Record<never, never>, Record<never, never>>,
    '/dydown/': RouteRecordInfo<'/dydown/', '/dydown', Record<never, never>, Record<never, never>>,
    '/exif/': RouteRecordInfo<'/exif/', '/exif', Record<never, never>, Record<never, never>>,
    '/json-yaml/': RouteRecordInfo<'/json-yaml/', '/json-yaml', Record<never, never>, Record<never, never>>,
    '/playground/': RouteRecordInfo<'/playground/', '/playground', Record<never, never>, Record<never, never>>,
    '/qrcode/': RouteRecordInfo<'/qrcode/', '/qrcode', Record<never, never>, Record<never, never>>,
    '/tools/': RouteRecordInfo<'/tools/', '/tools', Record<never, never>, Record<never, never>>,
    '/weather/': RouteRecordInfo<'/weather/', '/weather', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/base64/index.vue': {
      routes: '/base64/'
      views: never
    }
    'src/pages/bilidown/index.vue': {
      routes: '/bilidown/'
      views: never
    }
    'src/pages/dydown/index.vue': {
      routes: '/dydown/'
      views: never
    }
    'src/pages/exif/index.vue': {
      routes: '/exif/'
      views: never
    }
    'src/pages/json-yaml/index.vue': {
      routes: '/json-yaml/'
      views: never
    }
    'src/pages/playground/index.vue': {
      routes: '/playground/'
      views: never
    }
    'src/pages/qrcode/index.vue': {
      routes: '/qrcode/'
      views: never
    }
    'src/pages/tools/index.vue': {
      routes: '/tools/'
      views: never
    }
    'src/pages/weather/index.vue': {
      routes: '/weather/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
